language: r
dist: trusty
sudo: required
cache: packages

#apt_packages:
#  - libudunits2-dev

before_install:
#  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
#  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libproj-dev libgdal-dev
#  - sudo apt-get install -y libudunits2-dev libgdal-dev

compiler:
  - clang

warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: huNAaYm/zJMEYLiK7X/Saw7qUUOd24KFVWX2ASAuN6HB8k/5EHYAzC4yQ0PdyeTZB+Pd17KyzKKOLFTRjkpyEpzeKrGQHRTBUFWvmCrxAw2CrRzzB1DCplCgXYGE3TxwvVjcEMR9ruaLAxo9GQ0tR9W7GUlzIiguelJnsJJ7XnU=
