language: r
dist: trusty
sudo: required
cache: packages

before_install:
  - sudo apt-get install -y libproj-dev libgdal-dev

compiler:
  - clang

warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: huNAaYm/zJMEYLiK7X/Saw7qUUOd24KFVWX2ASAuN6HB8k/5EHYAzC4yQ0PdyeTZB+Pd17KyzKKOLFTRjkpyEpzeKrGQHRTBUFWvmCrxAw2CrRzzB1DCplCgXYGE3TxwvVjcEMR9ruaLAxo9GQ0tR9W7GUlzIiguelJnsJJ7XnU=
